### ISSUE TITLE
The test test_thread_safety throws exceptions

### ISSUE THREAD

**Issue by matanor** [IBM/unitxt#263]
The test [`test_thread_safety`](https://github.com/IBM/unitxt/blob/main/tests/test_random_utils.py#L56) throws the following exceptions:
```
Traceback (most recent call last): 
 File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner 
 self.run() 
 File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 870, in run 
 self._target(*self._args, **self._kwargs) 
 File "/home/runner/work/unitxt/unitxt/tests/test_random_utils.py", line 64, in thread_function 
 with nested_seed(): 
 File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/contextlib.py", line 113, in __enter__ 
 return next(self.gen) 
 File "/home/runner/work/unitxt/unitxt/src/unitxt/random_utils.py", line 30, in nested_seed 
 state = _thread_local.random.getstate() 
AttributeError: '_thread._local' object has no attribute 'random'
```
See for example [here](https://github.com/IBM/unitxt/actions/runs/6704673534/job/18217540543#step:8:26869). 

These are thrown by the threads created in the test, causing the threads to exit. However, the test does not fail, since it is not checked whether an exception was thrown by the threads.

The exception is thrown because the `random` attribute is not initialized for the created threads. So, when they try to get a nested seed ([here](https://github.com/IBM/unitxt/blob/main/tests/test_random_utils.py#L64)) an exception is thrown.

**Comment by matanor** [comment]
To reproduce locally:
Place a breakpoint [here](https://github.com/IBM/unitxt/blob/main/tests/test_random_utils.py#L90), run the test, and observe that 

```
results
[[None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]]
```
