### ISSUE TITLE
unitxt-explore fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by marukaz** [IBM/unitxt#602]
```
❯ unitxt-explore
Traceback (most recent call last):
  File "/Users/marukaz/.pyenv/versions/3.11.4/bin/unitxt-explore", line 8, in <module>
    sys.exit(launch())
             ^^^^^^^^
  File "/Users/marukaz/ghq/github.com/marukaz/unitxt/src/unitxt/ui/__init__.py", line 11, in launch
    from .run import demo
  File "/Users/marukaz/ghq/github.com/marukaz/unitxt/src/unitxt/ui/run.py", line 4, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

Of course I can install modules until error does not occur but it would be helpful if there is an instruction to install them in README

**Comment by elronbandel** [comment]
Fixed by https://github.com/IBM/unitxt/commit/ce2ca5b5ad135024385bc76483ba16ba1071e8d3
